---
- name: Set up Docker and deploy application on target machines
  hosts: all
  become: yes

  tasks:
    # Task 0: Ensure Python is installed
    - name: Ensure Python is installed
      package:
        name: python3
        state: present
      when: ansible_python_interpreter is not defined

    # Task 1: Update yum cache
    - name: Update yum cache
      yum:
        name: "*"
        update_cache: yes

    # Task 2: Install required system packages
    - name: Install required system packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    # Task 3: Add Docker repository
    - name: Add Docker repository
      yum_repository:
        name: docker-ce
        description: Docker CE Repository
        baseurl: https://download.docker.com/linux/centos/{{ ansible_distribution_major_version }}/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes

    # Task 4: Install Docker
    - name: Install Docker
      yum:
        name: docker-ce
        state: present

    # Task 5: Check Docker version
    - name: Check Docker version
      command: docker --version
      register: docker_version

    - name: Display Docker version
      debug:
        msg: "{{ docker_version.stdout }}"

    # Task 6: Ensure Docker service is running
    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    # Task 7: Pull Docker image
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: abdelrahmangad275/weather_app:latest
        source: pull

    # Task 8: Run Docker container
    - name: Run Docker container
      docker_container:
        name: weather-app
        image: abdelrahmangad275/weather_app:latest
        state: started
        ports:
          - "8081:80"
        restart_policy: always
